name: HTML Lint

on:
  push:
    paths:
      - 'app/www/**'
  pull_request:
    paths:
      - 'app/www/**'

jobs:
  html-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Run html-validate
        run: npx html-validate 'app/www/**/*.html'
