name: Release Tagging

on:
  pull_request:
    types: [closed]
permissions:
  contents: write

jobs:
  deploy_release:
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'release/') &&
      github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    environment: default
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Determine tag name
        id: tag
        run: |
            BRANCH="${{ github.event.pull_request.head.ref }}"
            TAG="${BRANCHrelease/}"
            if [ "$TAG" = "$BRANCH" ]; then
              echo "Branch name does not start with release/"
              exit 1
            fi
            echo "tag=test" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Sync site to S3 for release tagging
        run: |
          echo "tag=test" >> $GITHUB_OUTPUT
          aws s3 sync app/www/ s3://${{ vars.AWS_S3_BUCKET }}/releases/${{ steps.tag.outputs.tag }} --delete \
              --exclude 'node_modules/*' \
              --exclude 'package**' \
              --exclude 'Dockerfile' \
              --exclude '.dockerignore'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}

  push_tag_to_repo:
    runs-on: ubuntu-latest
    needs: deploy_release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push tag to repository
        run: |
          TAG=${{ needs.deploy_release.outputs.tag }}
          git tag -a "$TAG" -m "Release $TAG"
          git push origin "refs/tags/$TAG"
